name: ci

on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch and version
        env:
          REPO_TAG: ${{ github.ref_name }}
        id: set_branch_and_version
        run: |
          echo "BRANCH_NAME=${REPO_TAG##*.}" >> $GITHUB_ENV
          echo "VERSION=${REPO_TAG%.*}" >> $GITHUB_ENV

      - name: Determine app id
        run: |
          echo "Branch: $BRANCH_NAME"
          if [ "$BRANCH_NAME" == "experimental" ]; then
            echo "APP_ID=1890870" >> $GITHUB_ENV
          else
            echo "APP_ID=1874900" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: thewillard/arsa-test:$BRANCH_NAME, thewillard/arsa-test:$VERSION
          build-args: |
            STEAM_APP_ID=$APP_ID
