name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "*.*.*-*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch and version
        env:
          REPO_TAG: ${{ github.ref_name }}
        id: set_branch_and_version
        run: |
          BRANCH_NAME="${REPO_TAG##*.}"
          echo "Branch: $BRANCH_NAME"
          VERSION="${REPO_TAG%.*}"
          echo "Version: $VERSION"

      - name: Determine app id
        run: |
          if [ "$BRANCH_NAME" == "experimental" ]; then
            APP_ID=1890870
          else
            APP_ID=1874900
          fi
          echo "AppId: $APP_ID"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: thewillard/arsa-test:${{ vars.BRANCH_NAME }}, thewillard/arsa-test:${{ vars.VERSION }}
          build-args: |
            STEAM_APP_ID=${{ vars.APP_ID }}
